#!/usr/bin/env bash
pip install -r requirements.txt;
python -m nltk.downloader stopwords;
python -m nltk.downloader wordnet;
python -m nltk.downloader averaged_perceptron_tagger;
echo "#####################################################";
echo "Setup completed succesfully!!"